apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalcar-backend
  namespace: rentalcar
  labels:
    app: rentalcar-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rentalcar-backend
  template:
    metadata:
      labels:
        app: rentalcar-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: backend
          image: phucanhptit/rentalcar-be:latest
          ports:
            - containerPort: 8081  # Backend service
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://192.168.0.123:1434;database=CarRentalDB;encrypt=true;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dapaisme@0312"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: JWT_SECRET
              value: "404fdsfsdewrewtwrdfdsdf343254354334eter2B4B6250645367566B5970"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:4200"
        - name: sidecar-metrics
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100  
          

---
apiVersion: v1
kind: Service
metadata:
  name: rentalcar-backend
  namespace: rentalcar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9100"  # This should point to the Prometheus exporter's port
spec:
  selector:
    app: rentalcar-backend
  ports:
    - name: backend-port  # Name for the backend service port
      protocol: TCP
      port: 8081          # Service port for the backend
      targetPort: 8081    # Port on the container for the backend
      nodePort: 30004     # Optional NodePort for the backend   # Optional NodePort for the 
    - name: sidecar-metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30057
  type: NodePort


