apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalcar-frontend
  namespace: rentalcar
  labels:
    app: rentalcar-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentalcar-frontend
  template:
    metadata:
      labels:
        app: rentalcar-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: frontend
          image: phucanhptit/fe-rentalcarangular:latest
          ports:
            - containerPort: 80
        - name: sidecar-metrics
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: rentalcar-frontend
  namespace: rentalcar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: rentalcar-frontend
  ports:
    - protocol: TCP
      name: frontend
      port: 80
      targetPort: 80
      nodePort: 30001
    - protocol: TCP
      name: sidecar-metrics
      port: 9100
      targetPort: 9100
      nodePort: 30056
  type: NodePort
