apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rentalcar-ingress
  namespace: rentalcar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: frontend-backend-ingress
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rentalcar-backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rentalcar-frontend
                port:
                  number: 80
