apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: rentalcar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.8.0
          ports:
            - containerPort: 3100
          env:
            - name: LOKI_AUTH_ENABLED
              value: "false"
            - name: LOKI_SERVER_HTTP_LISTEN_PORT
              value: "3100"
            - name: LOKI_INGESTER_LIFECYCLER_ADDRESS
              value: "127.0.0.1"
            - name: LOKI_INGESTER_LIFECYCLER_RING_KVSTORE_STORE
              value: "inmemory"
            - name: LOKI_INGESTER_LIFECYCLER_RING_REPLICATION_FACTOR
              value: "1"
            - name: LOKI_INGESTER_CHUNK_IDLE_PERIOD
              value: "5m"
            - name: LOKI_INGESTER_CHUNK_RETAIN_PERIOD
              value: "30s"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_FROM
              value: "2020-05-15"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_STORE
              value: "boltdb"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_OBJECT_STORE
              value: "filesystem"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_SCHEMA
              value: "v11"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_INDEX_PREFIX
              value: "index_"
            - name: LOKI_SCHEMA_CONFIG_CONFIGS_0_INDEX_PERIOD
              value: "168h"
            - name: LOKI_STORAGE_BOLTDB_DIRECTORY
              value: "/tmp/loki/index"
            - name: LOKI_STORAGE_FILESYSTEM_DIRECTORY
              value: "/tmp/loki/chunks"
          volumeMounts:
            - name: storage
              mountPath: /tmp/loki
      volumes:
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: rentalcar
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30029
  type: NodePort