apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Interval between scrapes
    scrape_configs:
      - job_name: 'rentalcar-backend'
        static_configs:
          - targets: ['192.168.16.2:30004']  # Adjust based on your setup
        metrics_path: /actuator/prometheus
