apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: rentalcar
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Interval between scrapes
    scrape_configs:
      - job_name: 'rentalcar-backend'
        static_configs:
          - targets: ['rentalcar-backend:8081']  # Adjust based on your setup
        metrics_path: /actuator/prometheus
      - job_name: 'filestorageservice'
        static_configs:
          - targets: ['filestorageservice:8082']  # Adjust based on your setup
        metrics_path: /actuator/prometheus
      - job_name: 'global-metrics'
        static_configs:
          - targets: ['node-exporter:9100']  # Adjust based on your setup
        metrics_path: /metrics
      - job_name: 'rentalcar-frontend'
        static_configs:
          - targets: ['rentalcar-frontend:9100']  # Adjust based on your setup
        metrics_path: /metrics
      - job_name: 'node-exporter-backend'
        static_configs:
          - targets: ['rentalcar-backend:9100']  # Adjust based on your setup
        metrics_path: /metrics
      - job_name: 'node-exporter-fileservice'
        static_configs:
          - targets: ['filestorageservice:9100']  # Adjust based on your setup
        metrics_path: /metrics
      - job_name: 'node-exporter-postgres'
        static_configs:
          - targets: ['postgres-service:9100']  # Adjust based on your setup
        metrics_path: /metrics
