apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: rentalcar
data:
  promtail.yaml: |
    scrape_configs:
    - job_name: spring-boot-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: springboot
            app: rentalcar-backend
            __path__: /app/app/logs/*.log
            
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    # pipeline_stages:
    #   - json:
    #       expressions:
    #         timestamp: timestamp
    #         level: level
    #         message: message
    #   - labels:
    #       level:
    #   - timestamp:
    #       source: timestamp
    #       format: RFC3339Nano
    #   - output:
    #       source: message

